/**
 * Turns URL path segments into a storage key, or refuses.
 *
 * The one place in the system where a caller's path segments become a storage
 * key. Everywhere else a key is generated by `buildStorageKey` from a UUID and
 * never leaves the server, which is why this is the only function that has to
 * be suspicious of what it is given.
 */

/** C0 and C1 control characters. A NUL truncates a path in some layers. */
const CONTROL_CHARS = /[\u0000-\u001f\u007f-\u009f]/

/**
 * Rejects anything that could resolve somewhere other than where it reads.
 *
 * Three separate problems, each of which alone defeats a `startsWith` tenant
 * check:
 *
 *   1. `..` — `org/A/../B/x` starts with `org/A/` and resolves under `org/B/`.
 *      A prefix check on the raw string sees the prefix and misses the escape.
 *   2. Double decoding — Next already decodes catch-all params, so decoding
 *      them again turns `%252e%252e` into `..` AFTER any check that ran on the
 *      decoded-once form. The segments arrive decoded and are used as-is.
 *   3. A separator inside a segment — `/` or `\` smuggles extra path structure
 *      into what the router handed over as one component.
 */
export function keyFromSegments(segments: string[], requiredPrefix: string): string | null {
  if (segments.length === 0) return null

  for (const segment of segments) {
    if (segment === '' || segment === '.' || segment === '..') return null
    if (segment.includes('/') || segment.includes('\\')) return null
    if (CONTROL_CHARS.test(segment)) return null
  }

  const key = segments.join('/')

  // The tenant boundary, applied only after every segment has been shown to
  // carry no path structure of its own.
  if (!key.startsWith(requiredPrefix)) return null

  return key
}
