import { createHmac, randomBytes, timingSafeEqual } from 'node:crypto'
import { mkdir, readFile, rm, writeFile } from 'node:fs/promises'
import { dirname, join, resolve } from 'node:path'
import type { DocumentStorage, StoredObject } from './types'

/**
 * Local-disk storage, for development only.
 *
 * The same reasoning as the PGlite fallback for the database: `npm run dev`
 * should work with nothing provisioned. Production is Vercel Blob and this file
 * is never reachable there — `getStorage()` refuses to fall back when
 * NODE_ENV is production, so a missing token fails loudly instead of quietly
 * writing documents to a container's disk.
 *
 * It is not a Blob emulator. Privacy and URL expiry are properties of the real
 * service and are verified against it by the smoke suite.
 */
const ROOT = resolve(process.cwd(), '.data/blob')

/**
 * Keys are generated by the app and contain no user input, but this is the one
 * place a key becomes a filesystem path — so it is checked rather than trusted.
 *
 * `resolve` collapses `..` before the prefix check, which catches an escape out
 * of the root. It does NOT catch `org/A/../B/x`: that stays inside the root and
 * lands under a different tenant. So a `..` segment is refused outright rather
 * than normalised into something that looks fine.
 */
function pathFor(key: string): string {
  if (key.split('/').some((segment) => segment === '..' || segment === '.')) {
    throw new Error('Invalid storage key')
  }
  const full = resolve(ROOT, key)
  if (!full.startsWith(ROOT + '/')) throw new Error('Invalid storage key')
  return full
}

export class LocalDiskStorage implements DocumentStorage {
  async put(key: string, body: Buffer, contentType: string): Promise<StoredObject> {
    const path = pathFor(key)
    await mkdir(dirname(path), { recursive: true })
    await writeFile(path, body)
    await writeFile(`${path}.type`, contentType)
    return { key, size: body.length, contentType }
  }

  async get(key: string): Promise<Buffer> {
    return readFile(pathFor(key))
  }

  async signedDownloadUrl(
    key: string,
    options: { expiresInSeconds: number; downloadFilename?: string },
  ): Promise<string> {
    // The same shape as the real thing: an absolute URL that carries its own
    // authorization and expires. The download routes answer with a redirect,
    // and a redirect needs an absolute URL — a relative one is a 500 — so the
    // stand-in has to be reachable without a session exactly as a presigned
    // Blob URL is, which is what the signature is for.
    const expires = Date.now() + Math.min(Math.max(options.expiresInSeconds, 1), 300) * 1000
    const url = new URL(
      `/api/dev-blob/${key.split('/').map(encodeURIComponent).join('/')}`,
      process.env.SIGN_PUBLIC_URL ?? 'http://localhost:3000',
    )
    url.searchParams.set('expires', String(expires))
    if (options.downloadFilename) url.searchParams.set('filename', options.downloadFilename)
    url.searchParams.set('signature', signDevDownload(key, expires))
    return url.toString()
  }

  async delete(key: string): Promise<void> {
    await rm(pathFor(key), { force: true })
    await rm(`${pathFor(key)}.type`, { force: true })
  }

  async exists(key: string): Promise<boolean> {
    try {
      await readFile(pathFor(key))
      return true
    } catch {
      return false
    }
  }
}

/**
 * A per-process secret for the stand-in's signed URLs.
 *
 * On globalThis so Next's hot reload does not mint a fresh one on every edit
 * and invalidate a link someone just clicked. Never persisted, never shared:
 * a link is only ever valid against the process that issued it, which is all
 * a development download needs.
 */
const globalForSecret = globalThis as unknown as { __xtraSignDevBlobSecret?: Buffer }

function devSecret(): Buffer {
  if (!globalForSecret.__xtraSignDevBlobSecret) {
    globalForSecret.__xtraSignDevBlobSecret = randomBytes(32)
  }
  return globalForSecret.__xtraSignDevBlobSecret
}

function signDevDownload(key: string, expires: number): string {
  return createHmac('sha256', devSecret()).update(`${key}\n${expires}`).digest('base64url')
}

/** True only for a URL this process signed, for this key, that has not expired. */
export function verifyDevDownload(key: string, expires: string | null, signature: string | null): boolean {
  if (!expires || !signature) return false
  const expiresAt = Number(expires)
  if (!Number.isFinite(expiresAt) || expiresAt < Date.now()) return false

  const expected = Buffer.from(signDevDownload(key, expiresAt))
  const given = Buffer.from(signature)
  return expected.length === given.length && timingSafeEqual(expected, given)
}

export { ROOT as LOCAL_STORAGE_ROOT, join }
