import { mkdir, readFile, rm, writeFile } from 'node:fs/promises'
import { dirname, join, resolve } from 'node:path'
import type { DocumentStorage, StoredObject } from './types'

/**
 * Local-disk storage, for development only.
 *
 * The same reasoning as the PGlite fallback for the database: `npm run dev`
 * should work with nothing provisioned. Production is Vercel Blob and this file
 * is never reachable there — `getStorage()` refuses to fall back when
 * NODE_ENV is production, so a missing token fails loudly instead of quietly
 * writing documents to a container's disk.
 *
 * It is not a Blob emulator. Privacy and URL expiry are properties of the real
 * service and are verified against it by the smoke suite.
 */
const ROOT = resolve(process.cwd(), '.data/blob')

/**
 * Keys are generated by the app and contain no user input, but this is the one
 * place a key becomes a filesystem path — so it is checked rather than trusted.
 */
function pathFor(key: string): string {
  const full = resolve(ROOT, key)
  if (!full.startsWith(ROOT + '/')) throw new Error('Invalid storage key')
  return full
}

export class LocalDiskStorage implements DocumentStorage {
  async put(key: string, body: Buffer, contentType: string): Promise<StoredObject> {
    const path = pathFor(key)
    await mkdir(dirname(path), { recursive: true })
    await writeFile(path, body)
    await writeFile(`${path}.type`, contentType)
    return { key, size: body.length, contentType }
  }

  async get(key: string): Promise<Buffer> {
    return readFile(pathFor(key))
  }

  async signedDownloadUrl(key: string): Promise<string> {
    // Nothing signs anything here. Development downloads go through the app's
    // own authorized routes, which is what this URL is fed to.
    return `/api/dev-blob/${encodeURIComponent(key)}`
  }

  async delete(key: string): Promise<void> {
    await rm(pathFor(key), { force: true })
    await rm(`${pathFor(key)}.type`, { force: true })
  }

  async exists(key: string): Promise<boolean> {
    try {
      await readFile(pathFor(key))
      return true
    } catch {
      return false
    }
  }
}

export { ROOT as LOCAL_STORAGE_ROOT, join }
